### ISSUE TITLE
Errors when running on a CSS server

### ISSUE THREAD

**Issue by wladimir77** [Stewart-Anubis/Zr-Grenade-Effects-Anubis-Edition#2]
`
L 07/17/2021 - 19:39:47: SourceMod error session started
L 07/17/2021 - 19:39:47: Info (map "de_dust2") (file "d:\GamesServer\CSS1\css_servers\css_serv92ver4\cstrike\addons\sourcemod\logs\errors_20210717.log")
L 07/17/2021 - 19:39:47: [SM] Exception reported: Game event "player_spawned" does not exist
L 07/17/2021 - 19:39:47: [SM] Blaming: zr_grenade_effects_csgo.smx
L 07/17/2021 - 19:39:47: [SM] Call stack trace:
L 07/17/2021 - 19:39:47: [SM]   [0] HookEvent
L 07/17/2021 - 19:39:47: [SM]   [1] Line 176, zr_grenade_effects_csgo.sp::OnPluginStart
L 07/17/2021 - 19:39:47: [SM] Unable to load plugin "zr_grenade_effects_csgo.smx": Error detected in plugin startup (see error logs)
L 07/17/2021 - 19:39:50: [SM] Exception reported: Game event "player_spawned" does not exist
L 07/17/2021 - 19:39:50: [SM] Blaming: zr_grenade_effects_csgo_lite.smx
L 07/17/2021 - 19:39:50: [SM] Call stack trace:
L 07/17/2021 - 19:39:50: [SM]   [0] HookEvent
L 07/17/2021 - 19:39:50: [SM]   [1] Line 154, zr_grenade_effects_csgo_lite.sp::OnPluginStart
L 07/17/2021 - 19:39:50: [SM] Unable to load plugin "zr_grenade_effects_csgo_lite.smx": Error detected in plugin startup (see error logs)
`
How do I fix them?

**Comment by wladimir77** [comment]
I removed the error "player_spawned", compiled it, ran it, nothing has changed, the plugin does not work, although it is written in CSS
In the list it is present .cfg is created, but the result is 0.

**Comment by Stewart-Anubis** [comment]
Did you try to replace "player_spawned" with "player_spawn" ?

**Comment by wladimir77** [comment]
And he did so, but he does not want to work.

**Comment by wladimir77** [comment]
It turns out he seems to have got up, there are no errors, but it does not work. Although he loaded the model of the cube, but with a smoke grenade, nothing happens.

**Comment by Stewart-Anubis** [comment]
Yes. I changed this version only to be used with "Decoy", by a bug present in "smoke". This version only creates the ice grenade and slows down the zombies when they are on fire. The “fire hegrenade” effects function belong to the zombiereloaded settings itself.

**Comment by wladimir77** [comment]
Well, in principle, I need an ice grenade. So what can you do to get it?

**Comment by Stewart-Anubis** [comment]
You don't have "decoy"?

**Comment by Stewart-Anubis** [comment]
Then I will add the option to change the usage between "decoy" and "smoke" in the settings, although I strongly indicate to use "decoy" .

**Comment by wladimir77** [comment]
Lost in translation. Understood nothing, but very interesting. In general, there is
regular grenade (it works as an attacker), flash grenade (disabled), smoke grenade (should be ice but does not work). I translate through a translator. :)

**Comment by Stewart-Anubis** [comment]
I speak Portuguese Brazil, I also use a translator, what is your language?

**Comment by wladimir77** [comment]
Russian :)

**Comment by Stewart-Anubis** [comment]
Хорошо, я обновлю плагин и добавлю возможность использовать «дым». Подожди немного .

**Comment by wladimir77** [comment]
ok.

**Comment by Stewart-Anubis** [comment]
Test - Update 2.6

**Comment by wladimir77** [comment]
Tudo parece estar bem. A fumaça congela e há um cubo. Eu adormeci, desculpe.

**Comment by wladimir77** [comment]
E o repositório é sm-zombiereloaded-3-Franug-Edition.
É para você ou para o criador?

**Comment by Stewart-Anubis** [comment]
Depois vou olhar , a parte de som e comigo .
